services:
  _defaults:
    autowire: true
    autoconfigure: true

  MirandaLeyva\ContaoArchitectureReferences\Controller\:
    resource: "../../Controller/"

  MirandaLeyva\ContaoArchitectureReferences\Command\:
    resource: "../../Command/"

  MirandaLeyva\ContaoArchitectureReferences\Service\:
    resource: "../../Service/"
