services:
  _defaults:
    autowire: true
    autoconfigure: true

  MirandaLeyva\ContaoArchitectureReferences\Controller\:
    resource: "../../Controller/"

  MirandaLeyva\ContaoArchitectureReferences\Command\:
    resource: "../../Command/"
    tags:
      - { name: console.command }

  MirandaLeyva\ContaoArchitectureReferences\Service\:
    resource: "../../Service/"

  MirandaLeyva\ContaoArchitectureReferences\Service\ArchitectureReferenceImageFolderRepairService: ~

  MirandaLeyva\ContaoArchitectureReferences\Command\RepairArchitectureReferenceImagesByFolderCommand:
    arguments:
      $repairService: '@MirandaLeyva\ContaoArchitectureReferences\Service\ArchitectureReferenceImageFolderRepairService'
    tags:
      - { name: console.command }
